import "https://deno.land/x/xhr@0.1.0/mod.ts";

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
};

Deno.serve(async (req) => {
  if (req.method === 'OPTIONS') {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const { lead } = await req.json();
    if (!lead) {
      return new Response(JSON.stringify({ error: 'No lead provided' }), { status: 400, headers: { ...corsHeaders, 'Content-Type': 'application/json' } });
    }

    const supabaseUrl = Deno.env.get('SUPABASE_URL')!;
    const serviceKey = Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;
    const lovableApiKey = Deno.env.get('LOVABLE_API_KEY');

    const headers = {
      'Authorization': `Bearer ${serviceKey}`,
      'apikey': serviceKey,
      'Content-Type': 'application/json',
    };

    // Fetch active automation rules
    const rulesRes = await fetch(`${supabaseUrl}/rest/v1/automation_rules?is_enabled=eq.true&order=created_at.asc`, { headers });

    if (!rulesRes.ok) {
      console.error('Failed to fetch rules:', await rulesRes.text());
      return new Response(JSON.stringify({ executed: 0 }), { headers: { ...corsHeaders, 'Content-Type': 'application/json' } });
    }

    const rules = await rulesRes.json();
    const executed: string[] = [];
    const leadPriority = lead.priority || 'cold';

    for (const rule of rules) {
      // Check trigger match
      let matches = false;
      if (rule.trigger_type === 'new_lead') matches = true;
      else if (rule.trigger_type === leadPriority) matches = true;
      if (!matches) continue;

      // Skip delayed rules for now (no cron yet)
      if (rule.delay_minutes > 0) continue;

      const actionType = rule.action_type;
      const actionConfig = rule.action_config || {};
      let status = 'success';
      let resultData: any = {};

      try {
        // ===== ACTION: Generate AI message (WhatsApp / Email) =====
        if (actionType === 'whatsapp' || actionType === 'email') {
          if (lovableApiKey) {
            const msgRes = await fetch(`${supabaseUrl}/functions/v1/generate-lead-message`, {
              method: 'POST',
              headers: {
                'Authorization': `Bearer ${serviceKey}`,
                'Content-Type': 'application/json',
              },
              body: JSON.stringify({
                lead,
                messageType: actionConfig.message_type || actionType,
                language: actionConfig.language || 'es',
                targetApp: actionConfig.target_app || 'evofinz',
                templateType: actionConfig.template_type || 'first_contact',
              }),
            });

            if (msgRes.ok) {
              const msgData = await msgRes.json();
              resultData = { message: msgData.message, messageType: actionType, templateType: actionConfig.template_type };
            } else {
              const errText = await msgRes.text();
              console.error(`AI message generation failed for rule ${rule.name}:`, errText);
              status = 'failed';
              resultData = { error: errText };
            }
          } else {
            status = 'skipped';
            resultData = { reason: 'LOVABLE_API_KEY not configured' };
          }

          // Also mark as auto-contacted
          if (status === 'success') {
            await fetch(`${supabaseUrl}/rest/v1/quiz_leads?id=eq.${lead.id}`, {
              method: 'PATCH',
              headers: { ...headers, 'Prefer': 'return=minimal' },
              body: JSON.stringify({
                contacted_at: new Date().toISOString(),
                contact_notes: `[AUTO] ${actionType} generated by rule: ${rule.name}`,
              }),
            });
          }
        }

        // ===== ACTION: Auto-contact =====
        else if (actionType === 'auto_contact') {
          await fetch(`${supabaseUrl}/rest/v1/quiz_leads?id=eq.${lead.id}`, {
            method: 'PATCH',
            headers: { ...headers, 'Prefer': 'return=minimal' },
            body: JSON.stringify({
              contacted_at: new Date().toISOString(),
              contact_notes: `Auto-contacted by rule: ${rule.name}`,
            }),
          });
          resultData = { action: 'auto_contact' };
        }

        // ===== ACTION: Auto-tag =====
        else if (actionType === 'auto_tag') {
          const tagsToAdd = actionConfig.tags || [];
          if (tagsToAdd.length > 0) {
            const existingTags = lead.tags || [];
            const mergedTags = [...new Set([...existingTags, ...tagsToAdd])];
            await fetch(`${supabaseUrl}/rest/v1/quiz_leads?id=eq.${lead.id}`, {
              method: 'PATCH',
              headers: { ...headers, 'Prefer': 'return=minimal' },
              body: JSON.stringify({ tags: mergedTags }),
            });
            resultData = { tags_added: tagsToAdd, total_tags: mergedTags };
          } else {
            status = 'skipped';
            resultData = { reason: 'No tags configured' };
          }
        }

        // ===== ACTION: Auto-stage (pipeline) =====
        else if (actionType === 'auto_stage') {
          const stage = actionConfig.stage || 'new';
          await fetch(`${supabaseUrl}/rest/v1/quiz_leads?id=eq.${lead.id}`, {
            method: 'PATCH',
            headers: { ...headers, 'Prefer': 'return=minimal' },
            body: JSON.stringify({ pipeline_stage: stage }),
          });
          resultData = { stage };
        }

        // ===== ACTION: Auto follow-up =====
        else if (actionType === 'auto_followup') {
          const delayHours = actionConfig.followup_delay_hours || 72;
          const followupType = actionConfig.followup_type || 'call';
          const scheduledAt = new Date(Date.now() + delayHours * 60 * 60 * 1000).toISOString();

          await fetch(`${supabaseUrl}/rest/v1/lead_follow_ups`, {
            method: 'POST',
            headers: { ...headers, 'Prefer': 'return=minimal' },
            body: JSON.stringify({
              lead_id: lead.id,
              follow_up_type: followupType,
              scheduled_at: scheduledAt,
              notes: `[AUTO] Created by rule: ${rule.name}`,
              status: 'pending',
            }),
          });
          resultData = { scheduled_at: scheduledAt, type: followupType };
        }

        // Log as interaction
        await fetch(`${supabaseUrl}/rest/v1/lead_interactions`, {
          method: 'POST',
          headers: { ...headers, 'Prefer': 'return=minimal' },
          body: JSON.stringify({
            lead_id: lead.id,
            interaction_type: 'automation',
            direction: 'outbound',
            notes: `[AUTO] Rule "${rule.name}" → ${actionType} (${status})`,
          }),
        });

      } catch (actionErr) {
        console.error(`Action error for rule ${rule.name}:`, actionErr);
        status = 'failed';
        resultData = { error: String(actionErr) };
      }

      // ===== LOG to automation_logs =====
      await fetch(`${supabaseUrl}/rest/v1/automation_logs`, {
        method: 'POST',
        headers: { ...headers, 'Prefer': 'return=minimal' },
        body: JSON.stringify({
          rule_id: rule.id,
          lead_id: lead.id,
          action_type: actionType,
          status,
          result_data: resultData,
        }),
      });

      // ===== Update rule execution stats =====
      await fetch(`${supabaseUrl}/rest/v1/automation_rules?id=eq.${rule.id}`, {
        method: 'PATCH',
        headers: { ...headers, 'Prefer': 'return=minimal' },
        body: JSON.stringify({
          execution_count: (rule.execution_count || 0) + 1,
          last_executed_at: new Date().toISOString(),
        }),
      });

      executed.push(rule.name);
    }

    console.log(`Executed ${executed.length} automation rules for lead ${lead.id}:`, executed);

    return new Response(JSON.stringify({ executed: executed.length, rules: executed }), {
      headers: { ...corsHeaders, 'Content-Type': 'application/json' },
    });

  } catch (error) {
    console.error('Error in run-automations:', error);
    return new Response(JSON.stringify({ error: error.message }), {
      status: 500,
      headers: { ...corsHeaders, 'Content-Type': 'application/json' },
    });
  }
});
